version: '3.9'
networks:
  roboshop1:
    driver: bridge
services:
  web:
    image: web:v1
    container_name: web
    ports:
    - 80:80
    depends_on:
    - catalogue
    - user
    - cart
    - mysql
    - shipping
    - payment
    - ratings
  catalogue:
    image: catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  mongodb:
    image: mongodb:v1
    container_name: mongodb
  user:
    image: user:v1
    container_name: user
    depends_on:
      - redis
      - mongodb
  redis:
    image: redis
    container_name: redis
  mysql:
    image: mysql:v1
    container_name: mysql
  shipping:
    image: shipping:v1
    container_name: shipping
    depends_on:
      - mysql
  cart:
    image: cart:v1
    container_name: cart
    depends_on:
      - redis
      - catalogue
      - mongodb
      - user
  payment:
    image: payment:v1
    container_name: payment
    depends_on:
    - rabbitmq
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
  ratings:
    image: ratings:v1
    container_name: ratings
    depends_on:
      - mysql
  
       


     

  
  


    